language: node_js
node_js:
  - "9"
before_script:
  - npm run build
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npm run versionCommit
deploy:
  - provider: npm
    api_key:
      secure: "aEVZsHPwU1g8kfQxkZYdEBct5DFvoSQGPPRASwMMxkLhcmxwrooEMuLAloSljJUNfJw4DLQ3DpFTs5J4yft5RdMp8WxueFd2hFFwu9+FwnQwdctvVa8H9fPtSX6aEDCBvRDDWea0RKFELFvnrgWN1KlJOmgzSHY2hucB89hawfHMJRJwUCYJce4igBAe9xwarK//367+PBJXFTdOLxQHiAt10cHFDepq6SQX0rwFwLKYprtvPcBAao0n23YN/n4DPen5cC9FChyvHiv/UAXR6fxuGVQS9JKJlKWzK38SK6NwExTlzKeO+r8e27WUSntdjPgIs+hHiKhqkUp7UPAg5IC1t9IJkOJQyx3Cn4X178AlTdYbLmkXk5OVCGH1T3Zgbss4ljozNX890Wlc1hne1Zmgb1g9tyyu/DxXvNsBfNultOQWEyazkw3OUM/6qJztq8TvIxpcmyX4p8MvnOKW1oZCl0HZW9OY8RVBsGO7MWOtcepM5OqA8cpTDB16DMiFu8IUdfcvtBwSSH7h5GUNxUG/6N31xLYmEbyRUfNlNVgtrAPPuWJ97wNWt79a7T+kV6ZNwVM2SfLe8UYoEm9yGASQpTCVAg40SmyRkhTUgXwP82e6b72vVWhpV+TeiVPPIXtJoV4b6yKABvzSqCnrK3qrnUY0pCnN3j3FKUfz3j8="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "aEVZsHPwU1g8kfQxkZYdEBct5DFvoSQGPPRASwMMxkLhcmxwrooEMuLAloSljJUNfJw4DLQ3DpFTs5J4yft5RdMp8WxueFd2hFFwu9+FwnQwdctvVa8H9fPtSX6aEDCBvRDDWea0RKFELFvnrgWN1KlJOmgzSHY2hucB89hawfHMJRJwUCYJce4igBAe9xwarK//367+PBJXFTdOLxQHiAt10cHFDepq6SQX0rwFwLKYprtvPcBAao0n23YN/n4DPen5cC9FChyvHiv/UAXR6fxuGVQS9JKJlKWzK38SK6NwExTlzKeO+r8e27WUSntdjPgIs+hHiKhqkUp7UPAg5IC1t9IJkOJQyx3Cn4X178AlTdYbLmkXk5OVCGH1T3Zgbss4ljozNX890Wlc1hne1Zmgb1g9tyyu/DxXvNsBfNultOQWEyazkw3OUM/6qJztq8TvIxpcmyX4p8MvnOKW1oZCl0HZW9OY8RVBsGO7MWOtcepM5OqA8cpTDB16DMiFu8IUdfcvtBwSSH7h5GUNxUG/6N31xLYmEbyRUfNlNVgtrAPPuWJ97wNWt79a7T+kV6ZNwVM2SfLe8UYoEm9yGASQpTCVAg40SmyRkhTUgXwP82e6b72vVWhpV+TeiVPPIXtJoV4b6yKABvzSqCnrK3qrnUY0pCnN3j3FKUfz3j8="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "EvuFn7aW7+OkMnqGxJ0ZVtG79EQ/NW76jOjZ/n+mJFH8LeaRHEA5J2RkT/+UOEQFID2w6LmxktEY4VisSYZKHQZsdEBDqf4jmORupy2c0e3bge4qTWKTAGV43hyZr5OpWYYPNQuTMojR47Pj0CszbX2OwamXBYmi70XpMxF1C8IS/LuLVVN/WQIjxTtT2X525Lew8piyvGxXou4T7ohj0IpnBRdFVXhzwKF1+IeKnQaf1rCnSixuI+HTSAJ1BVKs9m+seHTnky4gJXUsSc1Kr/FVFLLo6HlgP3cW3TbZLrM2OCSEbipGQePXMp1/YNO1wB1lq6eJRIocXWMVKFzNT6ooNHQxx5dwSPGBgz8zLTz1S2N5mgdn+4gwTSGeodXRbfHzEN7fDPxhlsbGEReta8xF2D/i+ZUTfFJsrrWPWWDOKuL9/movR1V4nqOxzxJa+4x4DTV1suFRyr2f2UTowfk4g+PWrheubIkYBv3gij19KV3Bni4FuotLXdi3DcV0FMZkQ2uEPGPgdjkuZyY4oSczsp6EW+XudaYR4ugrjMZt8o164RjSjf6BAZE6rQ+EgWulLYBc89jU4owScbjAazOwybQRNn7SWVXFN6bp8T6aYLz6GIggZwoEsUKmgK+FMAhm8T7FbYOq/UvuImFvbipjouQKDOy1BawB9tOGW6g="
    on:
      tags: true
    skip_cleanup: true
