language: node_js

services:
- docker

node_js:
- "10"

before_script:
- npm run build

script:
- docker-compose up --build -d
- npm test -- --coverage --coverageReporters=lcov --coverageReporters=text
- docker-compose down --rmi all

# 2019-02-18 Temporarily disable Coveralls, it always complain in Travis CI with HTTP 422: Couldn't find a repository matching this job.
#            Tried to set COVERALLS_REPO_TOKEN but no luck
# - cat ./coverage/lcov.info | node_modules/.bin/coveralls

before_deploy:
- git config --local user.name "William Wong"
- git config --local user.email "compulim@hotmail.com"
- npx version-from-git --travis

deploy:
- provider: npm
  api_key:
    secure: "V2Mswnjo4cLI3vfw1tkwogPm2KOq8pF17sa04gE3jKYCILKvnF5tXNlrEH6l1VX/+vsAhd40l7XV8n054T/Wehj3oecrWkay521OR5ngNqNJ4CFgDkfIiu4URkxdTeK8/Iqy+YtX+FQoLN4TtYsmDvjWCBD9GzWLpAld0r8Tngx0rsGOpOjcNDpqPNLTj+9RuAl1hZsHD7bah2HMIPQfGmVMatNnr0yH2Y1R7Nu63b409QseOgj5r/J6eT29BvRKSoy9eKfEHqLrAI2dEGPsPCh4wYbRXSY5M+0VrkJZ22Vq1x5TgKdAeIpHEa9GuVC211pceWK+Mrc6lfsREjzuFsFk0WN8eYSsakkSkvVODj6cH0BpsoOiNJi6QptipejiUVwfKUF6urfsFVtAANmz3QSFQn4l5z9f1gBvaz3AqKCiqyImBbXGHS8EOgVQRabJiQ9BaSJ8jJcvrBazajN52Hqhdc63lxlMtO8wP+XJUaFfWJhCrvUqXLEO64uMtGqbmpvtoZCVvGwWXtJuXdCRzLW2e2nr5z5n9tBqkTCPS0q1pGaSTLgD5jPgW1UFVBOgzLc3OY+zZIC6COrkHwVbouu3eUCJU5kbHSBFq6hyQrSmCb3/JeP1xqUHRmXlbT0VDt/XuUDxnLc6hhFCAjo80quZO5qmXYyBbImeMja6dCg="
  email: "compulim@hotmail.com"
  on:
    branch: master
  skip_cleanup: true
  tag: master

- provider: npm
  api_key:
    secure: "V2Mswnjo4cLI3vfw1tkwogPm2KOq8pF17sa04gE3jKYCILKvnF5tXNlrEH6l1VX/+vsAhd40l7XV8n054T/Wehj3oecrWkay521OR5ngNqNJ4CFgDkfIiu4URkxdTeK8/Iqy+YtX+FQoLN4TtYsmDvjWCBD9GzWLpAld0r8Tngx0rsGOpOjcNDpqPNLTj+9RuAl1hZsHD7bah2HMIPQfGmVMatNnr0yH2Y1R7Nu63b409QseOgj5r/J6eT29BvRKSoy9eKfEHqLrAI2dEGPsPCh4wYbRXSY5M+0VrkJZ22Vq1x5TgKdAeIpHEa9GuVC211pceWK+Mrc6lfsREjzuFsFk0WN8eYSsakkSkvVODj6cH0BpsoOiNJi6QptipejiUVwfKUF6urfsFVtAANmz3QSFQn4l5z9f1gBvaz3AqKCiqyImBbXGHS8EOgVQRabJiQ9BaSJ8jJcvrBazajN52Hqhdc63lxlMtO8wP+XJUaFfWJhCrvUqXLEO64uMtGqbmpvtoZCVvGwWXtJuXdCRzLW2e2nr5z5n9tBqkTCPS0q1pGaSTLgD5jPgW1UFVBOgzLc3OY+zZIC6COrkHwVbouu3eUCJU5kbHSBFq6hyQrSmCb3/JeP1xqUHRmXlbT0VDt/XuUDxnLc6hhFCAjo80quZO5qmXYyBbImeMja6dCg="
  email: "compulim@hotmail.com"
  on:
    tags: true
  skip_cleanup: true

- provider: releases
  api_key:
    secure: "EvuFn7aW7+OkMnqGxJ0ZVtG79EQ/NW76jOjZ/n+mJFH8LeaRHEA5J2RkT/+UOEQFID2w6LmxktEY4VisSYZKHQZsdEBDqf4jmORupy2c0e3bge4qTWKTAGV43hyZr5OpWYYPNQuTMojR47Pj0CszbX2OwamXBYmi70XpMxF1C8IS/LuLVVN/WQIjxTtT2X525Lew8piyvGxXou4T7ohj0IpnBRdFVXhzwKF1+IeKnQaf1rCnSixuI+HTSAJ1BVKs9m+seHTnky4gJXUsSc1Kr/FVFLLo6HlgP3cW3TbZLrM2OCSEbipGQePXMp1/YNO1wB1lq6eJRIocXWMVKFzNT6ooNHQxx5dwSPGBgz8zLTz1S2N5mgdn+4gwTSGeodXRbfHzEN7fDPxhlsbGEReta8xF2D/i+ZUTfFJsrrWPWWDOKuL9/movR1V4nqOxzxJa+4x4DTV1suFRyr2f2UTowfk4g+PWrheubIkYBv3gij19KV3Bni4FuotLXdi3DcV0FMZkQ2uEPGPgdjkuZyY4oSczsp6EW+XudaYR4ugrjMZt8o164RjSjf6BAZE6rQ+EgWulLYBc89jU4owScbjAazOwybQRNn7SWVXFN6bp8T6aYLz6GIggZwoEsUKmgK+FMAhm8T7FbYOq/UvuImFvbipjouQKDOy1BawB9tOGW6g="
  on:
    tags: true
  skip_cleanup: true
